[theme]
primaryColor = "#9F86C0"              # Ungu pastel
backgroundColor = "#1E1E2F"           # Gelap keunguan modern
secondaryBackgroundColor = "#2D3142"  # Abu gelap lembut
textColor = "#E0E0E0"                 # Abu terang
